[
'click to shop',
'shop here',
'click to redeem',
'awesome clearance deals',
'clearance',
'mark downs',
'sale page',
'sales page',
'shop now',
'shop sale',
'click here for more clearance deals',
'online store',
'exclusive online sales',
'go to deal',
'go to the store',
'sale items',
'[click here to visit the site]',
'>> this one <<',
">>here's a link<<",
'buy now',
'buy it now!',
'buy it',
'check it out',
'check latest price',
'check our shipping charges',
'check this link right here now',
'check this out',
'check this out!!!',
'click here',
'click here for info',
'click here for more info',
'click the image to open in full size.',
'click this link here now',
'click to find out more',
'click to learn more',
'click to read',
'continue to external link',
"didn't buy them here, but it looks like this",
'get more information',
'get one here !',
'get one now',
'get redirected here',
'go here',
'go here and buy one',
'go to store',
'go to the site go to url',
'go to the website',
'go to website',
'here',
'here >>>',
'here is the exact one i had',
'here you go.',
'here)',
'here.',
"here's",
"here's a bit of a bargain",
"here's a summary page.",
"here's an example",
"here's more about it",
'in fact, look here for a top-notch selection!',
'in stock and ready to ship',
'in stock here',
'information',
"just saw it and it's got some good reviews.",
'learn here',
'learn more',
'learn this here now',
'listing of it',
'new addition',
'new one',
'nice promotion',
'one of these',
'online shops',
'open this website',
'over here',
'purchase',
'see here',
'see this',
'see our gift page',
'shop by price, color, locally and more',
'shop customs',
'shopping help',
'source',
'specials',
'take advantage of the special',
'take your pick',
'the link',
'their own version',
'there',
'these',
'these are great deals - everyone here is buying them for themselves and for gifts.',
'these are inexpensive and widely available.',
'these might have some potential.',
'this link',
'this one here',
'this one.',
'this page',
'this particular one',
'this.',
'this?',
'view link',
'view site',
'view website',
'visit',
'visit homepage',
'visit site',
'visit site now',
'visit this link',
'visit website',
'what our customers have said about us',
'where to buy',
'write a review',
]