[
'beginner’s guide to {keyword} at {brand}',
'here’s a great resource',
'{brand} guide: improving {keyword}',
'creating a {keyword} from {brand}',
'{brand} {keyword} assistance',
'{brand} / {keyword}',
'{brand}: {keyword}',
'about how to do {keyword} from {brand}',
'check out {brand} guide to {keyword}',
'how to do {keyword} – {brand}',
'how to {keyword} on {brand}',
'{brand}’s guide to {keyword}',
'guide by {brand} on {keyword}',
'about {keyword} - {brand}',
'{keyword} article from {brand}',
'{keyword} guide from {brand}',
'this comprehensive post by the {keyword} experts at {brand}',
'this great article from {brand} on {keyword} for',
'this {keyword} guide by {brand}',
'what is {keyword}? - {brand} (guide to {keyword})',
'{brand}`s piece on {keyword}',
'{brand}: how to create a {keyword}',
'this post from {brand} takes you step by step through the process of {keyword}',
'how to create a {keyword} [{brand}]',
'{brand} blog: what is {keyword}?',
'create a {keyword} (guide by {brand})',
'{brand}: {keyword}: a step-by-step guide',
'a comprehensive {keyword} resource from {brand}',
'{brand} - {keyword}',
'{brand}: {keyword} guide',
]