[
'{brand} study',
'according to {brand}',
'recent study by {brand}',
'{brand} survey',
'{brand} survey here',
'{brand} guide',
'a new guide from the writers at {brand}',
'a new guide from the researchers at {brand}',
'a study by {brand}',
'a survey by {brand}',
'{brand} conducted a study',
'{brand} conducted a survey',
'conducted by {brand}',
'new data from {brand}',
'guide ({brand})',
'check out this great article from {brand}',
'check out this guide via {brand}',
'great example can be found at {brand}',
'{brand} has a list of ',
'read this great article by {brand}',
'research by the staff of {brand}',
'{brand}',
'the website {brand}',
"{brand}'s website",
'new report from {brand}',
'read more on {brand}',
'{brand} explains',
'article by {brand}',
'check out this one from {brand}',
'delineated by our friends at {brand}',
'this {brand} piece',
'a new study from the researchers at {brand}',
'recent survey by {brand}',
'report from {brand}',
'{brand} conducted',
'{brand} report',
'{brand} research',
'study by {brand},',
'the {brand} blog',
'the {brand} website',
]