[
'{keyword} from {brand}',
'{brand} for {keyword}',
'to {brand} {keyword}',
'{brand} - what is {keyword}',
'access the {brand} {keyword} here',
'{keyword} such as {brand}',
'{brand} {keyword} app',
'{keyword}- {brand}',
'{brand} {keyword} definition',
'{brand} {keyword} free trial',
'{brand} {keyword} image',
'{brand} {keyword} ideas',
'access {brand} {keyword} here!',
'{keyword} by {brand}',
'{keyword} @ {brand}',
'{brand}’s free online {keyword}',
'{brand} {keyword} features',
'click here to signup with {brand} {keyword}',
'collaborating using {brand} {keyword}',
"what's new in {brand}'s {keyword}",
'award-winning {brand} honored as top-rated and best {keyword}',
"you can find more information on {brand}'s {keyword} here.",
'{brand} {keyword} is packed with essential features',
'{brand}’s accounting software',
"you can find more information on workflow rules on {brand} crm's help pages here.",
'{brand} {keyword}',
'{brand} {keyword} website',
'{brand} {keyword}: full feature set',
'{brand}’s {keyword}',
'{brand} offers a {keyword}',
'{brand} is a {keyword}',
'centrally manage {keyword} - {brand}',
'{brand} online {keyword}',
'{brand}’s free {keyword}',
'>> more information of {brand} {keyword} plus',
]