[
'{brand} - {keyword}',
'{brand} / {keyword}',
'{brand}: {keyword}',
"'{brand}' {keyword}",
'{brand} {keyword}',
'check out our {keyword} - {brand}',
'{brand} provides a {keyword}',
'{brand} identifies {keyword}',
'{brand} (for {keyword}',
'{brand}: check out our {keyword}',
'{keyword} called {brand}',
'{keyword} like {brand}',
'{keyword} {brand}',
'{keyword} - {brand}',
'use {brand} to improve your {keyword}',
'{brand} -- {keyword}',
'free {keyword} - {brand}',
'get {brand} {keyword}',
'{brand} - {keyword} in {city}',
'{brand} / {keyword} in {city}',
'{brand}: {keyword} in {city}',
"'{brand}' {keyword} in {city}",
'{brand} {keyword} in {city}',
'check out our {keyword} in {city} - {brand}',
'{brand} provides a {keyword} in {city}',
'{brand} identifies {keyword} in {city}',
'{brand} (for {keyword} in {city}',
'{brand}: check out our {keyword} in {city}',
'{keyword} in {city} called {brand}',
'{keyword} in {city} like {brand}',
'{keyword} in {city} {brand}',
'{keyword} in {city} - {brand}',
'use {brand} to improve your {keyword} in {city}',
'{brand} -- {keyword} in {city}',
'free {keyword} in {city} - {brand}',
'get {brand} {keyword} in {city}',
'{brand} - {keyword} in {state}',
'{brand} / {keyword} in {state}',
'{brand}: {keyword} in {state}',
"'{brand}' {keyword} in {state}",
'{brand} {keyword} in {state}',
'check out our {keyword} in {state} - {brand}',
'{brand} provides a {keyword} in {state}',
'{brand} identifies {keyword} in {state}',
'{brand} (for {keyword} in {state}',
'{brand}: check out our {keyword} in {state}',
'{keyword} in {state} called {brand}',
'{keyword} in {state}like {brand}',
'{keyword} in {state} {brand}',
'{keyword} in {state} - {brand}',
'{keyword} in {state} like {brand}',
'use {brand} to improve your {keyword} in {state}',
'{brand} -- {keyword} in {state}',
'free {keyword} in {state} - {brand}',
'get {brand} {keyword} in {state}',
'{brand} - {keyword} in {city}, {st}',
'{brand} / {keyword} in {city}, {st}',
'{brand}: {keyword} in {city}, {st}',
"'{brand}' {keyword} in {city}, {st}",
'{brand} {keyword} in {city}, {st}',
'check out our {keyword} in {city}, {st} - {brand}',
'{brand} provides a {keyword} in {city}, {st}',
'{brand} identifies {keyword} in {city}, {st}',
'{brand} (for {keyword} in {city}, {st}',
'{brand}: check out our {keyword} in {city}, {st}',
'{keyword} in {city}, {st} called {brand}',
'{keyword} in {city}, {st} like {brand}',
'{keyword} in {city}, {st} {brand}',
'{keyword} in {city}, {st} - {brand}',
'use {brand} to improve your {keyword} in {city}, {st}',
'{brand} -- {keyword} in {city}, {st}',
'free {keyword} in {city}, {st} - {brand}',
'get {brand} {keyword} in {city}, {st}',
]