[
'{keyword} online',
'{keyword} for sale',
'high quality {keyword}',
'a site to buy {keyword}',
'popular {keyword}',
'online {keyword}',
'{keyword} options',
'selling {keyword}',
'popular {keyword} site',
'a {keyword}',
'a site selling {keyword}',
'from a {keyword}',
'{keyword}',
'buy {keyword}',
'buy {keyword} online',
'order {keyword} online',
'found a {keyword} here',
'provider of {keyword}',
'at this {keyword}',
'this {keyword} noted',
'a {keyword} noted',
'as a {keyword} noted',
'in a {keyword} site',
'this {keyword} notes',
'this {keyword} suggests',
'this {keyword} says',
'this {keyword} reports',
'according to this {keyword}',
'{keyword} homepage',
'on a {keyword} site',
'a popular {keyword} notes',
'a trusted {keyword} suggests',
'an experienced {keyword} says',
'this quote from a {keyword}',
]