[
"{brand} blog",
"{brand}`s blog",
"{brand} anounced",
"posted to a {brand}`s blog",
"{brand} official blog",
"{brand} says",
"{brand} wrote in a blog post",
"{brand} said",
"{brand} said in a blog",
"according to {brand}",
"{brand} has announced",
"official {brand} blog",
"{brand} claims",
"{brand} officially announced",
"{brand} said in a blog post",
"{brand} announced today",
"{brand}`s latest blog post",
"{brand} post to a company blog",
"{brand} published a blog post",
"{brand} blog points out",
"{brand} argued in a blog post",
"{brand}`s statement on its official blog",
"as {brand} is explaining in its blog post",
"wrote {brand} president in a blog post",
"in a blog post {brand} wrote",
"{brand} blog entry",
"writes in the official {brand} blog",
"recent {brand} blog post",
"blog post on {brand} official blog",
"{brand} explained in a blog post",
"a post on the {brand}`s blog",
"according to a {brand} blog",
"{brand}`s recent blog post",
"statement posted on the {brand}`s blog",
"read more on {brand}`s official blog",
"from the {brand} blog",
"post ({brand})",
"check out this great article from {brand}",
"check out this blog post via {brand}",
"great example can be found at {brand}",
"{brand} blog post",
"{brand} explains",
"{brand} has a list of",
"read this great post by {brand}",
"research by the staff of {brand}",
"{brand}",
"the website {brand}",
"{brand}'s website",
"read more on {brand}",
"article by {brand}",
"check out this one from {brand}",
"delineated by our friends at {brand}",
"this {brand} piece",
"a new blog article from the writers at {brand}",
"a new article from the marketers at {brand}",
"a new piece of content from the writers at {brand}",
"a blog post by {brand}",
"a piece of content by {brand}",
"{brand} write an article",
"{brand} published an article",
"written by {brand}",
"new post from {brand}",
"new content from {brand}",
"recent post by {brand}",
"recent article by {brand}",
"blog post from {brand}",
"{brand} wrote",
"{brand} quotes",
"{brand} writes",
"{brand} blog article"
]