[
'blog post about {keyword} at {brand}',
'{brand}’s blog post about {keyword}',
'blog post by {brand} on {keyword}',
'about {keyword} - {brand}',
'{keyword} article from {brand}',
'{brand} article: improving {keyword}',
'{brand} blog: what is {keyword}?',
'{keyword} blog post from {brand}',
'this comprehensive post by the {keyword} experts at {brand}',
'this great article from {brand} on {keyword} for',
'this {keyword} blog post by {brand}',
'what is {keyword}? - {brand} (guide to {keyword})',
'{brand}`s piece on {keyword}',
'{brand}: {keyword}: a blog post',
'a long {keyword} blog post from {brand}',
'{brand} - {keyword}',
'{brand}: {keyword} blog post',
'{brand} {keyword} assistance',
'{brand} / {keyword}',
'{brand}: {keyword}',
'check out {brand} blog post to {keyword}',
'read this blog post from {brand}',
'post about {keyword} at {brand}',
'{brand}’s post about {keyword}',
'post by {brand} on {keyword}',
'{keyword} post from {brand}',
'this {keyword} post by {brand}',
'{brand}: {keyword}: a post',
'a long {keyword} post from {brand}',
'{brand}: {keyword} post',
'check out {brand} post to {keyword}',
'read this post from {brand}',
'article about {keyword} at {brand}',
'{brand}’s article about {keyword}',
'article by {brand} on {keyword}',
'this {keyword} article by {brand}',
'{brand}: {keyword}: a article',
'a long {keyword} article from {brand}',
'{brand}: {keyword} article',
'check out {brand} article to {keyword}',
'read this article from {brand}',
'blog article about {keyword} at {brand}',
'{brand}’s blog article about {keyword}',
'blog article by {brand} on {keyword}',
'{keyword} blog article from {brand}',
'this {keyword} blog article by {brand}',
'{brand}: {keyword}: a blog article',
'a long {keyword} blog article from {brand}',
'{brand}: {keyword} blog article',
'check out {brand} blog article to {keyword}',
'read this blog article from {brand}',
'blog content about {keyword} at {brand}',
'{brand}’s blog content about {keyword}',
'blog content by {brand} on {keyword}',
'{keyword} blog content from {brand}',
'this {keyword} blog content by {brand}',
'{brand}: {keyword}: a blog content',
'a long {keyword} blog content from {brand}',
'{brand}: {keyword} blog content',
'check out {brand} blog content to {keyword}',
'read this blog content from {brand}'
]