/*
 * Company Home Page
 */

KEYWORD_TOOL.PageType_keywordPlusPartOfKeyword['company_homepage'] = [
'{keyword} online',
'{keyword} for sale',
'high quality {keyword}',
'a site to buy {keyword}',
'popular {keyword}',
'online {keyword}',
'{keyword} options',
'selling {keyword}',
'popular {keyword} site',
'a {keyword}',
'a site selling {keyword}',
'from a {keyword}',
'{keyword}',
'buy {keyword}',
'buy {keyword} online',
'order {keyword} online',
'found a {keyword} here',
'provider of {keyword}',
'at this {keyword}',
'this {keyword} noted',
'a {keyword} noted',
'as a {keyword} noted',
'in a {keyword} site',
'this {keyword} notes',
'this {keyword} suggests',
'this {keyword} says',
'this {keyword} reports',
'according to this {keyword}',
'{keyword} homepage',
'on a {keyword} site',
'a popular {keyword} notes',
'a trusted {keyword} suggests',
'an experienced {keyword} says',
'this quote from a {keyword}',
];

KEYWORD_TOOL.PageType_branded['company_homepage'] = [
'{brand} website',
'{brand} official website',
'information from {brand}',
'about {brand}',
'available at {brand}`s website',
'{brand} homepage',
'{brand} official',
'more about {brand}',
'{brand} home page',
'visit {brand}`s official website',
'learn more about {brand}',
'{brand} site',
'as shown on {brand}`s website',
'{brand} announced',
'according to {brand}',
'source: {brand}',
'via {brand}',
'{brand}`s',
'right here on {brand}',
'at {brand}',
'to {brand}',
'by {brand}',
'in {brand}',
'from {brand}',
'{brand} noted',
'{brand} suggests',
'{brand} says',
'published on {brand}',
'this resource from {brand}',
'as {brand} notes',
'as {brand} reports',
'{brand} online',
'available via {brand}',
'1. {brand}',
'{brand} logo',
'visit {brand}',
'{brand}.',
'({brand})',
'{brand} packages',
'check out {brand} here.',
'"{brand}"',
'check out {brand}',
'check out {brand} here!',
'click here to go on {brand}',
'go to {brand} →',
'head to {brand}',
'head to the {brand} site',
'sign up for {brand}',
'the mighty {brand}',
'try {brand}',
'try {brand} for free',
'try {brand} for free today',
'use {brand}',
'visit {brand} here >>',
'{brand} -',
'{brand} ..!!',
'{brand} :',
'click here to visit {brand} for free',
'go to {brand}',
'go to {brand} and try for free',
'redirect to {brand}',
'use {brand} here',
'view {brand}',
'visit {brand} now >>>',
'you can try {brand}',
];

KEYWORD_TOOL.PageType_brandedPlusKeyword['company_homepage'] = [
'{brand} - {keyword}',
'{brand} / {keyword}',
'{brand}: {keyword}',
"'{brand}' {keyword}",
'{brand} {keyword}',
'check out our {keyword} - {brand}',
'{brand} provides a {keyword}',
'{brand} identifies {keyword}',
'{brand} - {keyword} platform',
'{brand} (for {keyword}',
'{brand}: check out our {keyword}',
'{keyword} by going to {brand}',
'{keyword} called {brand}',
'{keyword} like {brand}',
'{keyword} {brand}',
'{keyword} - {brand}',
'use {brand} to improve your {keyword}',
'{brand} -- {keyword}',
'free {keyword} - {brand}',
'get {brand} {keyword}',
];

KEYWORD_TOOL.PageType_justNatural['company_homepage'] = [
'homepage',
'click here',
'click here to contact',
'here',
'address',
'find a job',
'jobs',
'site',
'brand',
'here.',
'learn more',
'like this one',
'link',
'website',
'read more',
'read more about it here',
'read more...',
'check it out',
'sign up for a free trial',
'this',
'free trial',
'get it now..',
'more info',
'check here',
'check it out here',
'check out',
'this one',
'this page',
'click here to continue.',
'click here to view the listing >>',
'navigate here',
'look at this site',
'find more info',
'click to view listing >',
'visit',
'clicking here',
'pop over to these guys',
'navigate to this website',
'find this',
'click here now',
'browse this site',
'get more info',
'explore',
'original link',
'find out more',
'get started now',
'here’s a great place to get started',
'go to site >>',
'join here',
'more info >',
'start your trial',
'this site',
'try it now',
'try it out',
'try it out here',
'use this link',
'visit now',
'visit the site',
'visit their website',
'visit web site',
'visit website for more details',
'try this',
'what to do',
'get it',
'get it from here',
'get it here',
'get it now',
'go to site',
'go to the site go to url',
'go to website',
'view website',
'visit company website',
'visit their website here.',
'visit website for free trial',
'visit website here',
'[official website]',
'» view page',
];