/*
 * Local Business Service Page
 */

KEYWORD_TOOL.PageType_keywordPlusPartOfKeyword['local_business_service_page'] = [
'{keyword} in {state}',
'{keyword} for sale',
'high quality {keyword}',
'a site to buy {keyword}',
'popular {keyword}',
'online {keyword}',
'{keyword} options',
'selling {keyword}',
'a {keyword}',
'a site selling {keyword}',
'from a {keyword}',
'{keyword}',
'buy {keyword}',
'buy {keyword} online',
'order {keyword} online',
'found a {keyword} here',
'provider of {keyword}',
'at this {keyword}',
'this {keyword} noted',
'a {keyword} noted',
'as a {keyword} noted',
'in a {keyword} site',
'this {keyword} notes',
'this {keyword} suggests',
'this {keyword} says',
'this {keyword} reports',
'according to this {keyword}',
'{keyword} homepage',
'on a {keyword} site',
'a popular {keyword} notes',
'a trusted {keyword} suggests',
'an experienced {keyword} says',
'this quote from a {keyword}',
'{city} {keyword} are the finest',
'exactly where to find {keyword} in {city}',
'where to find {keyword} in {city}',
'how to find a {city} {keyword}',
'where to get a hold of the finest {city} {keyword}',
'where to locate the very best {keyword} in {city}',
'looking for a {keyword} in {city}?',
'top {keyword} {state}',
'from a {keyword} in {city}',
'according to a {keyword} in {city}',
'this page from a {keyword} in {city}',
'similar to this {keyword} in {city}',
'this interesting link to a {keyword} in {city}',
'as you can see from this {keyword} in {city}',
'{city} offers {keyword} like this',
'best ranked {keyword} in the {city}',
'more info on the best {keyword} in {city}',
'affordable {keyword} in {city}',
'this will help you to locate {keyword} in {city}',
'one of the best {keyword} in {city}',
'ranked as a top {keyword} in {city}',
'experienced {keyword} in {city}',
'one of the most popular {keyword} in {city}',
'resources from this {keyword}`s website in {city}',
'recomendation about best {keyword} in {city}',
'try this {keyword} located in {city}',
'highly recommended {keyword} from {city}',
'have you heard about this {keyword} in {city}?',
'any experience with {keyword} from {city}?',
'looking for good {keyword} in {city}',
'this {keyword} in {city} can help you',
'list of well ranked {keyword} in {city}',
'review of {keyword} in {city}',
'top ranking {keyword} in {city}',
'like this {keyword} in {city}',
'this information from a {keyword} in {city}',
'as this {keyword} in {city} is suggesting',
'top {keyword} {st}',
'looking for a {keyword} in {state}?',
'looking for a {keyword} in {st}?',
'according to a {keyword} in {city}, {st}',
'this page from a {keyword} in {city}, {st}',
'similar to this {keyword} in {city}, {st}',
'as you can see from this {keyword} in {city}, {st}',
'best ranked {keyword} in {city}, {st}',
'more info on the best {keyword} in {city}, {st}',
'affordable {keyword} in {city}, {st}',
'higly recommended {keyword} from {city}',
'as this {keyword} in {city}, {st} is suggesting',
'one of the best {keyword} in {city}, {st}',
'ranked as a top {keyword} in {city}, {st}',
'experienced {keyword} in {city}, {st}',
'one of the most popular {keyword} in {city}, {st}',
'recomendation about best {keyword} in {city}, {st}',
'try this {keyword} located in {city}, {st}',
'higly recommended {keyword} from {city}, {st}',
'have you heard about this {keyword} in {city}, {st}?',
'any experience with {keyword} from {city}, {st}?',
'looking for good {keyword} in {city}, {st}',
'this {keyword} in {city} can help you, {st}',
'list of well ranked {keyword} in {city}, {st}',
'review of {keyword} in {city}, {st}',
'top ranking {keyword} in {city}, {st}',
'like this {keyword} in {city}, {st}',
'this information from a {keyword} in {city}, {st}',
'one of the best {keyword} in {state}',
'ranked as a top {keyword} in {state}',
'experienced {keyword} in {state}',
'one of the most popular {keyword} in {state}',
'recomendation about best {keyword} in {state}',
'try this {keyword} located in {state}',
'highly recommended {keyword} from {state}',
'have you heard about this {keyword} in {state}?',
'any experience with {keyword} from{state}?',
'looking for good {keyword} in {state}',
'this {keyword} in {state} can help you',
'list of well ranked {keyword} in {state}',
'review of {keyword} in {state}',
'top ranking {keyword} in {state}',
'like this {keyword} in {state}',
'this information from a {keyword} in {state}',
'as this {keyword} in {state} is suggesting',
'this {keyword} in {city} noted',
'a {keyword} in {city} noted',
'as a {keyword} in {city} noted',
'in a {keyword} in {city} site',
'this {keyword} in {city} notes',
'this {keyword} in {city} suggests',
'this {keyword} in {city} says',
'this {keyword} in {city} reports',
'according to this {keyword} in {city} ',
'{keyword} in {city} homepage',
'on a {keyword} in {city} site',
'a popular {keyword} in {city} notes',
'a trusted {keyword} in {city} suggests',
'an experienced {keyword} in {city} says',
'this quote from a {keyword} in {city}',
'this {keyword} in {city}, {st} noted',
'a {keyword} in {city}, {st} noted',
'as a {keyword} in {city}, {st} noted',
'in a {keyword} in {city}, {st} site',
'this {keyword} in {city}, {st} notes',
'this {keyword} in {city}, {st} suggests',
'this {keyword} in {city}, {st} says',
'this {keyword} in {city}, {st} reports',
'according to this {keyword} in {city}, {st} ',
'{keyword} in {city}, {st} homepage',
'on a {keyword} in {city}, {st} site',
'a popular {keyword} in {city}, {st} notes',
'a trusted {keyword} in {city}, {st} suggests',
'an experienced {keyword} in {city}, {st} says',
'this quote from a {keyword} in {city}, {st}',
'this {keyword} in {state} noted',
'a {keyword} in {state} noted',
'as a {keyword} in {state} noted',
'in a {keyword} in {state} site',
'this {keyword} in {state} notes',
'this {keyword} in {state} suggests',
'this {keyword} in {state} says',
'this {keyword} in {state} reports',
'according to this {keyword} in {state}',
'{keyword} in {state} homepage',
'on a {keyword} in {state} site',
'a popular {keyword} in {state} notes',
'a trusted {keyword} in {state} suggests',
'an experienced {keyword} in {state} says',
'this quote from a {keyword} in {state}',
'according to a {keyword}',
'this page from a {keyword}',
'similar to this {keyword}',
'this interesting link to a {keyword}',
'as you can see from this {keyword}',
'best ranked {keyword}',
'more info on the best {keyword}',
'affordable {keyword}',
'this will help you to locate {keyword}',
'one of the best {keyword}',
'ranked as a top {keyword}',
'experienced {keyword}',
'one of the most popular {keyword}',
'resources from this {keyword}`s website',
'recomendation about best {keyword}',
'try this {keyword} located',
'highly recommended {keyword}',
'have you heard about this {keyword}?',
'looking for good {keyword}',
'this {keyword} can help you',
'review of {keyword}',
'top ranking {keyword}',
'like this {keyword}',
'this information from a {keyword}',
'as this {keyword} is suggesting',
'how to find a {keyword}',
'where to get a hold of the finest {keyword}',
'looking for a {keyword} ?',
'offers {keyword} like this',
'try this {keyword}',
'higly recommended {keyword}',
'any experience with {keyword}?',
'list of well ranked {keyword}',
];

KEYWORD_TOOL.PageType_branded['local_business_service_page'] = [
'{brand} website',
'{brand} official website',
'information from {brand}',
'about {brand}',
'available at {brand}`s website',
'{brand} homepage',
'{brand} official',
'more about {brand}',
'{brand} home page',
'visit {brand}`s official website',
'learn more about {brand}',
'{brand} site',
'as shown on {brand}`s website',
'{brand} announced',
'according to {brand}',
'source: {brand}',
'via {brand}',
'{brand}`s',
'right here on {brand}',
'at {brand}',
'to {brand}',
'by {brand}',
'in {brand}',
'from {brand}',
'{brand} noted',
'{brand} suggests',
'{brand} says',
'published on {brand}',
'this resource from {brand}',
'as {brand} notes',
'as {brand} reports',
'{brand} online',
'available via {brand}',
'1. {brand}',
'{brand} logo',
'visit {brand}',
'{brand} inner page',
'{brand}.',
'({brand})',
'{brand} info',
'check out {brand} here.',
'{brand}',
'check out {brand}',
'check out {brand} here!',
'click here to go on {brand}',
'go to {brand} →',
'head to {brand}',
'head to the {brand} site',
'sign up for {brand}',
'the mighty {brand}',
'try {brand}',
'try {brand} for a free quote',
'try {brand} for a free consultation',
'use {brand}',
'visit {brand} here >>',
'{brand} -',
'{brand} ..!!',
'{brand} :',
'click here to visit {brand} for free',
'go to {brand}',
'go to {brand} and try for free',
'redirect to {brand}',
'use {brand} here',
'view {brand}',
'visit {brand} now >>>',
'you can try {brand}',
'the local business {brand}',
];

KEYWORD_TOOL.PageType_brandedPlusKeyword['local_business_service_page'] = [
'{brand} - {keyword}',
'{brand} / {keyword}',
'{brand}: {keyword}',
"'{brand}' {keyword}",
'{brand} {keyword}',
'check out our {keyword} - {brand}',
'{brand} provides a {keyword}',
'{brand} identifies {keyword}',
'{brand} (for {keyword}',
'{brand}: check out our {keyword}',
'{keyword} called {brand}',
'{keyword} like {brand}',
'{keyword} {brand}',
'{keyword} - {brand}',
'use {brand} to improve your {keyword}',
'{brand} -- {keyword}',
'free {keyword} - {brand}',
'get {brand} {keyword}',
'{brand} - {keyword} in {city}',
'{brand} / {keyword} in {city}',
'{brand}: {keyword} in {city}',
"'{brand}' {keyword} in {city}",
'{brand} {keyword} in {city}',
'check out our {keyword} in {city} - {brand}',
'{brand} provides a {keyword} in {city}',
'{brand} identifies {keyword} in {city}',
'{brand} (for {keyword} in {city}',
'{brand}: check out our {keyword} in {city}',
'{keyword} in {city} called {brand}',
'{keyword} in {city} like {brand}',
'{keyword} in {city} {brand}',
'{keyword} in {city} - {brand}',
'use {brand} to improve your {keyword} in {city}',
'{brand} -- {keyword} in {city}',
'free {keyword} in {city} - {brand}',
'get {brand} {keyword} in {city}',
'{brand} - {keyword} in {state}',
'{brand} / {keyword} in {state}',
'{brand}: {keyword} in {state}',
"'brand}' {keyword} in {state}",
'{brand} {keyword} in {state}',
'check out our {keyword} in {state} - {brand}',
'{brand} provides a {keyword} in {state}',
'{brand} identifies {keyword} in {state}',
'{brand} (for {keyword} in {state}',
'{brand}: check out our {keyword} in {state}',
'{keyword} in {state} called {brand}',
'{keyword} in {state}like {brand}',
'{keyword} in {state} {brand}',
'{keyword} in {state} - {brand}',
'{keyword} in {state} like {brand}',
'use {brand} to improve your {keyword} in {state}',
'{brand} -- {keyword} in {state}',
'free {keyword} in {state} - {brand}',
'get {brand} {keyword} in {state}',
'{brand} - {keyword} in {city}, {st}',
'{brand} / {keyword} in {city}, {st}',
'{brand}: {keyword} in {city}, {st}',
"'{brand}' {keyword} in {city}, {st}",
'{brand} {keyword} in {city}, {st}',
'check out our {keyword} in {city}, {st} - {brand}',
'{brand} provides a {keyword} in {city}, {st}',
'{brand} identifies {keyword} in {city}, {st}',
'{brand} (for {keyword} in {city}, {st}',
'{brand}: check out our {keyword} in {city}, {st}',
'{keyword} in {city}, {st} called {brand}',
'{keyword} in {city}, {st} like {brand}',
'{keyword} in {city}, {st} {brand}',
'{keyword} in {city}, {st} - {brand}',
'use {brand} to improve your {keyword} in {city}, {st}',
'{brand} -- {keyword} in {city}, {st}',
'free {keyword} in {city}, {st} - {brand}',
'get {brand} {keyword} in {city}, {st}',
];

KEYWORD_TOOL.PageType_justNatural['local_business_service_page'] = [
'homepage',
'click here',
'click here to contact',
'here',
'address',
'find a job',
'jobs',
'site',
'brand',
'here.',
'learn more',
'like this one',
'link',
'website',
'read more',
'read more about it here',
'read more...',
'check it out',
'get it now..',
'more info',
'check here',
'check it out here',
'check out',
'this one',
'this page',
'click here to continue.',
'click here to view the listing >>',
'navigate here',
'look at this site',
'find more info',
'click to view listing >',
'visit',
'clicking here',
'pop over to these guys',
'navigate to this website',
'find this',
'click here now',
'browse this site',
'get more info',
'explore',
'original link',
'find out more',
'get started now',
'here’s a great place to get started',
'go to site >>',
'join here',
'more info >',
'this site',
'try it now',
'try it out',
'try it out here',
'use this link',
'visit now',
'visit the site',
'visit their website',
'visit web site',
'visit website for more details',
'try this',
'what to do',
'get it',
'get it from here',
'get it here',
'get it now',
'go to site',
'go to the site go to url',
'go to website',
'view website',
'visit company website',
'visit their website here.',
'visit website here',
'[official website]',
'» view page',
];