[
'visit',
'blog entry',
'website',
'dig this',
'section-by-section guide',
'a company that offers',
'pop over to these guys',
'goes on to describe',
'some ideas',
'a company that evaluates',
'this article',
'this',
'step-by-step guide',
'you can read the guide here',
'published a study',
'this article explains what it is, and why it is important',
'original link',
'this guide',
'this guide tells you all you need to know',
'check out this blog post',
'you do it yourself',
'this handy guide',
'this link explains',
'this one',
'click here',
'new report',
'read this comprehensive article',
'a company that helps',
'the online resource',
'click here to continue',
'click here to read the full article',
'free guide',
'visit website',
'guide',
'recent report',
'try this',
'some research',
'ran a recent survey',
'guides',
'study',
'here',
'online resource',
'great ideas for getting started',
'research they conducted',
'a premier study',
'their post',
'here.',
'learn more',
'a company that teaches',
'studies',
'like this one',
'clicking here',
'go to resource',
'a few of their recent reports',
'a few of our recent reports',
'link',
'this page',
'on this article',
'great article',
'a discussion',
'they surveyed and studied',
'study just released',
'read more',
'what to do',
'get more info',
'published',
'read more about it here',
'read more...',
'resources',
'the general idea here',
'great section on their site',
'recent study',
'“how to” documents',
'read the full study here.',
'navigate here',
'look at this site',
'find more info',
'my review here',
'information online',
'conducted a survey',
'navigate to this website',
'find this',
'click here now',
'browse this site',
'check here',
'click here to read',
'free tools and services',
'here are a couple of suggestions to get you started',
'click here to read the full report.',
'studies show',
'more info',
'here’s a great place to get started',
'click here to read the entire article',
'conducted a study',
'check out this blog',
'definitely check it out',
]