/*
 * Blog Content
 */

KEYWORD_TOOL.PageType_keywordPlusPartOfKeyword['blog_content'] = [
'advantages of {keyword}',
'also known as {keyword}',
'an excellent article to {keyword}',
'{keyword} article for',
'article to grow {keyword}',
'choose {keyword}',
'concept of {keyword}',
'decent article about {keyword}',
'different approaches to {keyword}',
'effective {keyword}',
'everything you need to know about {keyword}',
'article to {keyword}',
'introduction to {keyword} and how to',
"it's also about {keyword}.",
'learn more about {keyword}.',
'learn much more about {keyword}',
'{keyword} is still an important part of',
'{keyword} is one of',
'{keyword} methods',
'{keyword} opportunities',
'{keyword} practices',
'{keyword} strategies',
'{keyword} strategies & examples',
'{keyword} strategies and techniques',
'article for {keyword} here',
'{keyword} are one of the most important',
'looking for {keyword}',
'more about {keyword}',
'more on {keyword} can be learned here.',
'on this {keyword} article',
'refresher on {keyword}',
'{keyword} basics',
'{keyword} campaign',
'{keyword} article',
'the term "{keyword}"',
'this article tells you all you need to know about {keyword}',
'this handy {keyword} article',
'what {keyword} is',
'in {keyword}',
'{keyword} operates',
'learning about {keyword}',
'what is {keyword}',
'focused on other forms of {keyword}',
'{keyword} made simple',
'focus on {keyword}',
'{keyword} blog post',
'using {keyword}',
'definition of {keyword}',
'depends on your {keyword} strategy',
'build an {keyword} strategy',
'top {keyword} strategies',
'specifically about {keyword}',
'understand what {keyword} is',
'what the heck is {keyword}',
'think about {keyword}',
'understanding the definition of {keyword}',
'collection of {keyword}',
'how to write a {keyword}',
'your {keyword} article',
'{keyword} post',
'{keyword} ideas',
'composing your {keyword}',
'develop a {keyword}',
'{keyword} is an essential tool',
'a strong {keyword}',
'{keyword} development',
'having a {keyword}',
'good {keyword}',
'full {keyword}',
'detailed and structured {keyword}',
'well-built {keyword}',
'your {keyword}',
'the {keyword}',
'a robust {keyword}',
'interested to see the {keyword}',
'{keyword} method',
'comprehensive {keyword}',
'making a {keyword}',
'clear and detailed {keyword}',
'look online for {keyword}',
'detailed {keyword}',
'elements of a {keyword}',
'well-constructed {keyword}',
'create a solid {keyword}',
'help in getting their {keyword} made',
'a viable {keyword}',
'help forming a {keyword}',
'how to create a professional {keyword}',
'put together a {keyword}',
'articles on building a {keyword}',
'some best {keyword}s',
'actual {keyword}',
'creating an alluring {keyword}',
'putting together a {keyword}',
'a fantastic article on how to {keyword}',
'a good article on {keyword}',
'article on {keyword}',
'basic {keyword}',
'check out how to do {keyword}',
'click here to learn more about how to do {keyword}',
'do proper {keyword}',
'do some {keyword}',
'do thorough {keyword}',
'endless ways to do {keyword}',
'essential {keyword} on your own',
'get started with {keyword}',
'here’s a blog post on {keyword}',
'here’s a great article to {keyword}',
'how to conduct {keyword}',
'how to do {keyword}',
'how to do {keyword} and how to implement it',
'how to do {keyword} and how to implement it for free',
'how to perform {keyword}',
'read this awesome blog post on how to do {keyword}',
'an article to {keyword}',
];

KEYWORD_TOOL.PageType_branded['blog_content'] = [
'{brand} blog',
'{brand}`s blog',
'{brand} anounced',
'posted to a {brand}`s blog',
'{brand} official blog',
'{brand} says',
'{brand} wrote in a blog post',
'{brand} said',
'{brand} said in a blog',
'according to {brand}',
'{brand} has announced',
'official {brand} blog',
'{brand} claims',
'{brand} officially announced',
'{brand} said in a blog post',
'{brand} announced today',
'{brand}`s latest blog post',
'{brand} post to a company blog',
'{brand} published a blog post',
'{brand} blog points out',
'{brand} argued in a blog post',
'{brand}`s statement on its official blog',
'as {brand} is explaining in its blog post',
'wrote {brand} president in a blog post',
'in a blog post {brand} wrote',
'{brand} blog entry',
'writes in the official {brand} blog',
'recent {brand} blog post',
'blog post on {brand} official blog',
'{brand} explained in a blog post',
'a post on the {brand}`s blog',
'according to a {brand} blog',
'{brand}`s recent blog post',
'statement posted on the {brand}`s blog',
'read more on {brand}`s official blog',
'from the {brand} blog',
'post ({brand})',
'check out this great article from {brand}',
'check out this blog post via {brand}',
'great example can be found at {brand}',
'{brand} blog post',
'{brand} explains',
'{brand} has a list of',
'read this great post by {brand}',
'research by the staff of {brand}',
'{brand}',
'the website {brand}',
"{brand}'s website",
'read more on {brand}',
'article by {brand}',
'check out this one from {brand}',
'delineated by our friends at {brand}',
'this {brand} piece',
'a new blog article from the writers at {brand}',
'a new article from the marketers at {brand}',
'a new piece of content from the writers at {brand}',
'a blog post by {brand}',
'a piece of content by {brand}',
'{brand} write an article',
'{brand} published an article',
'written by {brand}',
'new post from {brand}',
'new content from {brand}',
'recent post by {brand}',
'recent article by {brand}',
'blog post from {brand}',
'{brand} wrote',
'{brand} quotes',
'{brand} writes',
'{brand} blog article',
];

KEYWORD_TOOL.PageType_brandedPlusKeyword['blog_content'] = [
'blog post about {keyword} at {brand}',
'{brand}’s blog post about {keyword}',
'blog post by {brand} on {keyword}',
'about {keyword} - {brand}',
'{keyword} article from {brand}',
'{brand} article: improving {keyword}',
'{brand} blog: what is {keyword}?',
'{keyword} blog post from {brand}',
'this comprehensive post by the {keyword} experts at {brand}',
'this great article from {brand} on {keyword} for',
'this {keyword} blog post by {brand}',
'what is {keyword}? - {brand} (guide to {keyword})',
'{brand}`s piece on {keyword}',
'{brand}: {keyword}: a blog post',
'a long {keyword} blog post from {brand}',
'{brand} - {keyword}',
'{brand}: {keyword} blog post',
'{brand} {keyword} assistance',
'{brand} / {keyword}',
'{brand}: {keyword}',
'check out {brand} blog post to {keyword}',
'read this blog post from {brand}',
'post about {keyword} at {brand}',
'{brand}’s post about {keyword}',
'post by {brand} on {keyword}',
'{keyword} post from {brand}',
'this {keyword} post by {brand}',
'{brand}: {keyword}: a post',
'a long {keyword} post from {brand}',
'{brand}: {keyword} post',
'check out {brand} post to {keyword}',
'read this post from {brand}',
'article about {keyword} at {brand}',
'{brand}’s article about {keyword}',
'article by {brand} on {keyword}',
'this {keyword} article by {brand}',
'{brand}: {keyword}: a article',
'a long {keyword} article from {brand}',
'{brand}: {keyword} article',
'check out {brand} article to {keyword}',
'read this article from {brand}',
'blog article about {keyword} at {brand}',
'{brand}’s blog article about {keyword}',
'blog article by {brand} on {keyword}',
'{keyword} blog article from {brand}',
'this {keyword} blog article by {brand}',
'{brand}: {keyword}: a blog article',
'a long {keyword} blog article from {brand}',
'{brand}: {keyword} blog article',
'check out {brand} blog article to {keyword}',
'read this blog article from {brand}',
'blog content about {keyword} at {brand}',
'{brand}’s blog content about {keyword}',
'blog content by {brand} on {keyword}',
'{keyword} blog content from {brand}',
'this {keyword} blog content by {brand}',
'{brand}: {keyword}: a blog content',
'a long {keyword} blog content from {brand}',
'{brand}: {keyword} blog content',
'check out {brand} blog content to {keyword}',
'read this blog content from {brand}',
];

KEYWORD_TOOL.PageType_justNatural['blog_content'] = [
'blog post',
'in a blog post',
'this article tells you all you need to know',
'this handy article',
'this link explains',
'this one',
'this page',
'website',
'navigate here',
'look at this site',
'find more info',
'my review here',
'visit',
'dig this',
'pop over to these guys',
'navigate to this website',
'find this',
'click here now',
'browse this site',
'check here',
'more info',
'get more info',
'read this comprehensive article',
'original link',
'you can read the article here',
'great section on their site',
'here’s a great place to get started',
'go to blog article',
'step-by-step article',
'section-by-section article',
'clicking here',
'you do it yourself',
'free tools and services',
'online blog article',
'great ideas for getting started',
'visit website',
'click here to read',
'information online',
'blog articles',
'here are a couple of suggestions to get you started',
'click here to read the entire article',
'try this',
'what to do',
'check out this blog',
'check out this blog post',
'click here to read the full article',
'definitely check it out',
'here’s a great blog article',
'some ideas',
'some research',
'their post',
'a company that evaluates',
'a company that helps',
'a company that offers',
'a company that teaches',
'a discussion',
'a few of our recent reports',
'a few of their recent reports',
'a premier study',
'click here to read the full report.',
'wrote an article',
'wrote a blog post',
'new article',
'published',
'published an article',
'ran a recent post',
'read the full post here.',
'recent content',
'recent post',
'research they conducted',
'article they wrote',
'article shows',
'article',
'article just released',
'the online blog article',
'they wrote and published',
];