/*
 * Company Service Page
 */

KEYWORD_TOOL.PageType_keywordPlusPartOfKeyword['company_service_page'] = [
'{keyword}',
'{keyword} best practices',
'{keyword} business',
'{keyword} features',
'{keyword} for small businesses',
'{keyword} reviews',
'{keyword}...',
'{keyword}:',
'all things {keyword}',
'best {keyword}',
'best {keyword} for',
'best possible {keyword}',
'brand in the {keyword} industry',
'bring your {keyword} to the future',
'choose a {keyword}',
'choosing the right {keyword}',
'click here to learn about {keyword}',
'discover the best {keyword}',
'example {keyword}',
'example of {keyword}',
'extraordinary {keyword}',
'having a good {keyword}',
'how a {keyword} can help',
'how to choose {keyword}',
'i want to learn more about {keyword}',
'in a capable {keyword}',
'leading {keyword}',
'learn about a {keyword}',
'learn more about {keyword}',
'manage {keyword}',
'managing {keyword}',
'most popular {keyword}',
'most user-friendly {keyword}',
'one of the top {keyword}',
'plenty of great {keyword} out there',
'purchase {keyword}',
'right {keyword} for you',
'several {keyword}',
'specialised {keyword}',
'the number one {keyword}',
'there are online {keyword}',
'there is {keyword}',
'today’s best overall {keyword} option',
'web based {keyword}',
'you can learn more about {keyword}',
];

KEYWORD_TOOL.PageType_branded['company_service_page'] = [
'collaborating using {brand}',
'sign in to your {brand} plus ...',
'{brand}’s offering',
'{brand}',
'understanding {brand}',
'visit {brand} website',
'learn more about {brand}',
'{brand} website here.',
'log into {brand}',
'more information of {brand} crm',
'new {brand} offerings',
'{brand}.com',
'{brand}’s lead capture form',
'sign in to your {brand} account',
"what's new in {brand}",
'alternative called {brand}',
'configuring {brand}...',
'buy from {brand}',
'{brand},',
'{brand} announced',
'{brand} lets you',
'{brand} crm features',
'{brand} official website',
'{brand} support',
'click here to learn more about {brand}',
'{brand}’s landing page',
'{brand}:',
'{brand} website',
'{brand} documentation',
'a {brand} product',
"click here to view {brand}'s pricing information",
'derived from {brand} best practices (click for details)',
'if you’re really interested in finding out more about {brand}, you can find their website here.',
'{brand} ideas',
'{brand} has a lot',
'{brand} offers an amazing option',
'click here to signup with {brand}',
'{brand} site',
'{brand} journey',
'{brand} content',
'if you’re interested in {brand}, you can find their website here.',
'visit {brand}',
'you can visit the {brand} website to learn more',
];

KEYWORD_TOOL.PageType_brandedPlusKeyword['company_service_page'] = [
'{keyword} from {brand}',
'{brand} for {keyword}',
'to {brand} {keyword}',
'{brand} - what is {keyword}',
'access the {brand} {keyword} here',
'{keyword} such as {brand}',
'{brand} {keyword} app',
'{keyword}- {brand}',
'{brand} {keyword} definition',
'{brand} {keyword} free trial',
'{brand} {keyword} image',
'{brand} {keyword} ideas',
'access {brand} {keyword} here!',
'{keyword} by {brand}',
'{keyword} @ {brand}',
'{brand}’s free online {keyword}',
'{brand} {keyword} features',
'click here to signup with {brand} {keyword}',
'collaborating using {brand} {keyword}',
"what's new in {brand}'s {keyword}",
'award-winning {brand} honored as top-rated and best {keyword}',
"you can find more information on {brand}'s {keyword} here.",
'{brand} {keyword} is packed with essential features',
'{brand}’s accounting software',
"you can find more information on workflow rules on {brand} crm's help pages here.",
'{brand} {keyword}',
'{brand} {keyword} website',
'{brand} {keyword}: full feature set',
'{brand}’s {keyword}',
'{brand} offers a {keyword}',
'{brand} is a {keyword}',
'centrally manage {keyword} - {brand}',
'{brand} online {keyword}',
'{brand}’s free {keyword}',
'>> more information of {brand} {keyword} plus',
];

KEYWORD_TOOL.PageType_justNatural['company_service_page'] = [
'read more',
'look here',
'view their full list of features',
'information on pricing is available here',
'modern day software',
'view website',
'link',
'30-day trial',
'this',
'plenty of software',
'totally free',
'learn more by visiting this page',
'limited-time offer',
'totally, 100% free',
'view full pricing',
'the right software',
'identify',
'view site',
'as the reviews attest',
'many solutions on the market',
'read more...',
'here’s',
'software program',
'by visiting this website you will discover how',
'full advantage',
'many benefits',
'check it out',
'ideas',
'check out pricing',
'learn more',
'click here to learn more',
'more',
'more detail',
'there are others',
'get it now',
'company’s site',
'view online',
'which programs',
'compare our features',
'most user-friendly',
'completely free of charge',
'details',
'continue',
'rave reviews',
'features',
'number one solution',
"don't miss the demo.",
'here',
'set up an account,',
'the most popular of which',
'visit website',
'official website',
'open site',
'product tour',
'reportedly used',
'this website explains',
'visit',
'you can learn more here.',
'a company that evaluates',
'a company that helps',
'a company that offers',
'detailed break down here',
'the features they offer',
'check out the latest features...',
'click this link',
'click this link here now',
'click this over here now',
'click to visit',
'clicking here',
'see for yourself',
'see this here',
'see this page',
'see website',
'sign up',
'sign up now!',
'signing up here',
'signup here',
'try here',
'try it now>>',
'try it out here',
'try this product',
'try this web-site',
'view product website',
'visit here',
'visit homepage',
'visit my website',
'visit site',
'visit the website',
'visit their site',
'visit this page',
'visit this web-site',
'why not check here',
'why not do that out',
'why not look here',
];