/*
 * Ecommerce Product Page
 */

KEYWORD_TOOL.PageType_keywordPlusPartOfKeyword['ecommerce_product_page'] = [
'{keyword} online',
'{keyword} for sale',
'high quality {keyword}',
'a place to buy {keyword}',
'popular {keyword} store',
'online {keyword} store',
'{keyword} options',
'{keyword} review',
'review of {keyword}',
'selling {keyword}',
'popular {keyword}',
'{keyword} supplier',
'online {keyword} supplier',
'buy {keyword}',
'order {keyword} online',
'found a {keyword} here',
'huge range of {keyword}',
'one stop shop for {keyword}',
'a wide variety of {keyword}',
'get {keyword} deals here',
'{keyword}: shop here',
'best {keyword}',
'{keyword} styles',
'{keyword} equipment',
'{keyword} discount',
'buy cheap {keyword}',
'enjoy savings on {keyword}',
'get “{keyword}” deals here',
'best {keyword} for men',
'these {keyword} are',
'like these {keyword}',
'get {keyword}',
'good site for {keyword}',
'several {keyword}',
'​all about {keyword}',
'discount {keyword}',
'a particular {keyword}',
'a version of {keyword}',
'a {keyword}',
'about {keyword}',
'american made {keyword}',
'are we talking about the same {keyword}?',
'best brand of {keyword}',
'best brand {keyword}',
'best rated {keyword}',
'buy {keyword} online',
'buy high quality {keyword} at affordable prices.',
'cool {keyword}',
'good {keyword}',
'great {keyword}',
'here are the specs on this {keyword}',
'how much is a {keyword}',
'{keyword} supplies',
'{keyword} set',
'{keyword} sets',
'{keyword} shop',
'{keyword} site',
'{keyword} store',
'{keyword} on the net',
'{keyword} ship free',
'large selection of {keyword}',
'limited edition {keyword}',
'{keyword} here',
'most popular {keyword}',
'new {keyword}',
'not all {keyword} have the same quality',
'one of the better {keyword}',
'{keyword} are in stock',
'variations of {keyword}',
'{keyword} series',
'personalized {keyword}',
'{keyword} page',
'{keyword} with',
'premium {keyword}',
'some formidable {keyword} here...',
'{keyword}:',
'the iconic {keyword}',
'these and a host of other {keyword}',
'this {keyword} absolutely does',
'this is an awesome {keyword}',
'this is the {keyword} that i want to get next.',
'this {keyword}',
'this {keyword} here',
'this series of {keyword}',
'top rated {keyword} brands',
'top rated {keyword}',
'top {keyword}',
'what is the best brand of {keyword}',
'what is the best {keyword} brand',
'whats a good {keyword}',
'what {keyword} do you use',
'where to buy {keyword}',
'who makes the best {keyword}',
];

KEYWORD_TOOL.PageType_branded['ecommerce_product_page'] = [
'{brand}: shop here',
'similar ones available on {brand}',
'{brand} deals',
"{brand}'s sale page",
'a link to the {brand}',
'discounted at the {brand}',
'enjoy free shipping on {brand}',
'from {brand}',
'{brand} company',
'get your {brand} new coupon codes and deals',
'go directly to {brand}',
'go to {brand}',
'{brand} sale & deals',
'{brand} reviews',
'{brand} link for more info',
'{brand} shows "in stock"',
'{brand} store',
'{brand},',
'{brand}.',
'link to buy it at {brand}',
'new pages from the {brand}',
'redirect to {brand}',
'reviews over at {brand}',
'shop @ {brand}',
'special deals from the {brand}',
'the {brand} presents',
'they got cool stuff {brand}',
'this product at {brand}',
'this one from {brand}',
'visit {brand}',
];

KEYWORD_TOOL.PageType_brandedPlusKeyword['ecommerce_product_page'] = [
'{brand} {keyword}',
'{brand} ({keyword})',
'{keyword} by {brand}',
'order a {keyword} from {brand}',
'{brand} {keyword} shop',
'buy {keyword} online from {brand}',
'check out {keyword} from {brand}',
'{brand} - free shipping on most {keyword}',
'{keyword}, boohoo',
'{keyword} at {brand}.com',
'{keyword} - {brand}',
'{keyword} | {brand} - everyday free shipping',
'business attire for women | {brand}',
'{keyword} at {brand}',
'{keyword} from {brand}',
'{brand} - {keyword}',
'discounted {keyword} from {brand}',
'{keyword}, designed by {brand}',
'{brand} {keyword} of all kinds',
'{brand}’s {keyword}',
'{brand} discount {keyword}',
'{brand} exclusive {keyword}',
'{brand} has since released their discounted prices on {keyword}.',
'{keyword} at the {brand}',
'{brand} makes some of the nicest {keyword}',
'order your {keyword} today at the {brand}',
'this {keyword} from {brand}',
'top {keyword} - {brand}',
'{brand} / {keyword}',
];

KEYWORD_TOOL.PageType_justNatural['ecommerce_product_page'] = [
'click to shop',
'shop here',
'click to redeem',
'awesome clearance deals',
'clearance',
'mark downs',
'sale page',
'sales page',
'shop now',
'shop sale',
'click here for more clearance deals',
'online store',
'exclusive online sales',
'go to deal',
'go to the store',
'sale items',
'[click here to visit the site]',
'>> this one <<',
">>here's a link<<",
'buy now',
'buy it now!',
'buy it',
'check it out',
'check latest price',
'check our shipping charges',
'check this link right here now',
'check this out',
'check this out!!!',
'click here',
'click here for info',
'click here for more info',
'click the image to open in full size.',
'click this link here now',
'click to find out more',
'click to learn more',
'click to read',
'continue to external link',
"didn't buy them here, but it looks like this",
'get more information',
'get one here !',
'get one now',
'get redirected here',
'go here',
'go here and buy one',
'go to store',
'go to the site go to url',
'go to the website',
'go to website',
'here',
'here >>>',
'here is the exact one i had',
'here you go.',
'here)',
'here.',
"here's",
"here's a bit of a bargain",
"here's a summary page.",
"here's an example",
"here's more about it",
'in fact, look here for a top-notch selection!',
'in stock and ready to ship',
'in stock here',
'information',
"just saw it and it's got some good reviews.",
'learn here',
'learn more',
'learn this here now',
'listing of it',
'new addition',
'new one',
'nice promotion',
'one of these',
'online shops',
'open this website',
'over here',
'purchase',
'see here',
'see this',
'see our gift page',
'shop by price, color, locally and more',
'shop customs',
'shopping help',
'source',
'specials',
'take advantage of the special',
'take your pick',
'the link',
'their own version',
'there',
'these',
'these are great deals - everyone here is buying them for themselves and for gifts.',
'these are inexpensive and widely available.',
'these might have some potential.',
'this link',
'this one here',
'this one.',
'this page',
'this particular one',
'this.',
'this?',
'view link',
'view site',
'view website',
'visit',
'visit homepage',
'visit site',
'visit site now',
'visit this link',
'visit website',
'what our customers have said about us',
'where to buy',
'write a review',
];