/*
 * Local Business Home Page
 */

KEYWORD_TOOL.PageType_keywordPlusPartOfKeyword['local_business_homepage'] = [
'{keyword} in {state}',
'{keyword} for sale',
'high quality {keyword}',
'a site to buy {keyword}',
'popular {keyword}',
'online {keyword}',
'{keyword} options',
'selling {keyword}',
'a {keyword}',
'a site selling {keyword}',
'from a {keyword}',
'buy {keyword}',
'buy {keyword} online',
'order {keyword} online',
'found a {keyword} here',
'provider of {keyword}',
'at this {keyword}',
'this {keyword} noted',
'a {keyword} noted',
'as a {keyword} noted',
'in a {keyword} site',
'this {keyword} notes',
'this {keyword} suggests',
'this {keyword} says',
'this {keyword} reports',
'according to this {keyword}',
'{keyword} homepage',
'on a {keyword} site',
'a popular {keyword} notes',
'a trusted {keyword} suggests',
'an experienced {keyword} says',
'this quote from a {keyword}',
'{city} {keyword} are the finest',
'exactly where to find {keyword} in {city}',
'where to find {keyword} in {city}',
'how to find a {city} {keyword}',
'where to get a hold of the finest {city} {keyword}',
'where to locate the very best {keyword} in {city}',
'looking for a {keyword} in {city}?',
'top {keyword} {state}',
];

KEYWORD_TOOL.PageType_branded['local_business_homepage'] = [
'{brand} website',
'{brand} official website',
'information from {brand}',
'about {brand}',
'available at {brand}`s website',
'{brand} homepage',
'{brand} official',
'more about {brand}',
'{brand} home page',
'visit {brand}`s official website',
'learn more about {brand}',
'{brand} site',
'as shown on {brand}`s website',
'{brand} announced',
'according to {brand}',
'source: {brand}',
'via {brand}',
'{brand}`s',
'right here on {brand}',
'at {brand}',
'to {brand}',
'by {brand}',
'in {brand}',
'from {brand}',
'{brand} noted',
'{brand} suggests',
'{brand} says',
'published on {brand}',
'this resource from {brand}',
'as {brand} notes',
'as {brand} reports',
'{brand} online',
'available via {brand}',
'1. {brand}',
'{brand} logo',
'visit {brand}',
'{brand}.',
'({brand})',
'{brand} info',
'check out {brand} here.',
'{brand}',
'check out {brand}',
'check out {brand} here!',
'click here to go on {brand}',
'go to {brand} →',
'head to {brand}',
'head to the {brand} site',
'sign up for {brand}',
'the mighty {brand}',
'try {brand}',
'try {brand} for a free quote',
'try {brand} for a free consultation',
'use {brand}',
'visit {brand} here >>',
'{brand} -',
'{brand} ..!!',
'{brand} :',
'click here to visit {brand} for free',
'go to {brand}',
'go to {brand} and try for free',
'redirect to {brand}',
'use {brand} here',
'view {brand}',
'visit {brand} now >>>',
'you can try {brand}',
'the local business {brand}',
];

KEYWORD_TOOL.PageType_brandedPlusKeyword['local_business_homepage'] = [
'{brand} - {keyword}',
'{brand} / {keyword}',
'{brand}: {keyword}',
"'{brand}' {keyword}",
'{brand} {keyword}',
'check out our {keyword} - {brand}',
'{brand} provides a {keyword}',
'{brand} identifies {keyword}',
'{brand} (for {keyword}',
'{brand}: check out our {keyword}',
'{keyword} called {brand}',
'{keyword} like {brand}',
'{keyword} {brand}',
'{keyword} - {brand}',
'use {brand} to improve your {keyword}',
'{brand} -- {keyword}',
'free {keyword} - {brand}',
'get {brand} {keyword}',
'{brand} - {keyword} in {city}',
'{brand} / {keyword} in {city}',
'{brand}: {keyword} in {city}',
"'{brand}' {keyword} in {city}",
'{brand} {keyword} in {city}',
'check out our {keyword} in {city} - {brand}',
'{brand} provides a {keyword} in {city}',
'{brand} identifies {keyword} in {city}',
'{brand} (for {keyword} in {city}',
'{brand}: check out our {keyword} in {city}',
'{keyword} in {city} called {brand}',
'{keyword} in {city} like {brand}',
'{keyword} in {city} {brand}',
'{keyword} in {city} - {brand}',
'use {brand} to improve your {keyword} in {city}',
'{brand} -- {keyword} in {city}',
'free {keyword} in {city} - {brand}',
'get {brand} {keyword} in {city}',
'{brand} - {keyword} in {state}',
'{brand} / {keyword} in {state}',
'{brand}: {keyword} in {state}',
"'{brand}' {keyword} in {state}",
'{brand} {keyword} in {state}',
'check out our {keyword} in {state} - {brand}',
'{brand} provides a {keyword} in {state}',
'{brand} identifies {keyword} in {state}',
'{brand} (for {keyword} in {state}',
'{brand}: check out our {keyword} in {state}',
'{keyword} in {state} called {brand}',
'{keyword} in {state}like {brand}',
'{keyword} in {state} {brand}',
'{keyword} in {state} - {brand}',
'{keyword} in {state} like {brand}',
'use {brand} to improve your {keyword} in {state}',
'{brand} -- {keyword} in {state}',
'free {keyword} in {state} - {brand}',
'get {brand} {keyword} in {state}',
'{brand} - {keyword} in {city}, {st}',
'{brand} / {keyword} in {city}, {st}',
'{brand}: {keyword} in {city}, {st}',
"'{brand}' {keyword} in {city}, {st}",
'{brand} {keyword} in {city}, {st}',
'check out our {keyword} in {city}, {st} - {brand}',
'{brand} provides a {keyword} in {city}, {st}',
'{brand} identifies {keyword} in {city}, {st}',
'{brand} (for {keyword} in {city}, {st}',
'{brand}: check out our {keyword} in {city}, {st}',
'{keyword} in {city}, {st} called {brand}',
'{keyword} in {city}, {st} like {brand}',
'{keyword} in {city}, {st} {brand}',
'{keyword} in {city}, {st} - {brand}',
'use {brand} to improve your {keyword} in {city}, {st}',
'{brand} -- {keyword} in {city}, {st}',
'free {keyword} in {city}, {st} - {brand}',
'get {brand} {keyword} in {city}, {st}',
];

KEYWORD_TOOL.PageType_justNatural['local_business_homepage'] = [
'homepage',
'click here',
'click here to contact',
'here',
'address',
'find a job',
'jobs',
'site',
'brand',
'here.',
'learn more',
'like this one',
'link',
'website',
'read more',
'read more about it here',
'read more...',
'check it out',
'get it now..',
'more info',
'check here',
'check it out here',
'check out',
'this one',
'this page',
'click here to continue.',
'click here to view the listing >>',
'navigate here',
'look at this site',
'find more info',
'click to view listing >',
'visit',
'clicking here',
'pop over to these guys',
'navigate to this website',
'find this',
'click here now',
'browse this site',
'get more info',
'explore',
'original link',
'find out more',
'get started now',
'here’s a great place to get started',
'go to site >>',
'join here',
'more info >',
'this site',
'try it now',
'try it out',
'try it out here',
'use this link',
'visit now',
'visit the site',
'visit their website',
'visit web site',
'visit website for more details',
'try this',
'what to do',
'get it',
'get it from here',
'get it here',
'get it now',
'go to site',
'go to the site go to url',
'go to website',
'view website',
'visit company website',
'visit their website here.',
'visit website here',
'[official website]',
'» view page',
];