[
'read more',
'look here',
'view their full list of features',
'information on pricing is available here',
'modern day software',
'view website',
'link',
'30-day trial',
'this',
'plenty of software',
'totally free',
'learn more by visiting this page',
'limited-time offer',
'totally, 100% free',
'view full pricing',
'the right software',
'identify',
'view site',
'as the reviews attest',
'many solutions on the market',
'read more...',
'here’s',
'software program',
'by visiting this website you will discover how',
'full advantage',
'many benefits',
'check it out',
'ideas',
'check out pricing',
'learn more',
'click here to learn more',
'more',
'more detail',
'there are others',
'get it now',
'company’s site',
'view online',
'which programs',
'compare our features',
'most user-friendly',
'completely free of charge',
'details',
'continue',
'rave reviews',
'features',
'number one solution',
"don't miss the demo.",
'here',
'set up an account,',
'the most popular of which',
'visit website',
'official website',
'open site',
'product tour',
'reportedly used',
'this website explains',
'visit',
'you can learn more here.',
'a company that evaluates',
'a company that helps',
'a company that offers',
'detailed break down here',
'the features they offer',
'check out the latest features...',
'click this link',
'click this link here now',
'click this over here now',
'click to visit',
'clicking here',
'see for yourself',
'see this here',
'see this page',
'see website',
'sign up',
'sign up now!',
'signing up here',
'signup here',
'try here',
'try it now>>',
'try it out here',
'try this product',
'try this web-site',
'view product website',
'visit here',
'visit homepage',
'visit my website',
'visit site',
'visit the website',
'visit their site',
'visit this page',
'visit this web-site',
'why not check here',
'why not do that out',
'why not look here',
]